# Generated by Django 2.1.2 on 2018-11-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='noOfGamesPlayed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='noOfGamesWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='totalScore',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
