# Generated by Django 2.1.2 on 2018-11-16 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1Forbidden', picklefield.fields.PickledObjectField(editable=False)),
                ('player2Forbidden', picklefield.fields.PickledObjectField(editable=False)),
                ('activePlayerIs1', models.BooleanField()),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPieces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfSunkShips', models.IntegerField()),
                ('positions', picklefield.fields.PickledObjectField(editable=False)),
                ('whichShipsSunk', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player1Pieces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1Pieces', to='play.PlayerPieces'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='player2Pieces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2Pieces', to='play.PlayerPieces'),
        ),
    ]
