# Generated by Django 2.1.2 on 2018-11-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameID',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
