# Generated by Django 2.1.2 on 2018-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_game_gameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1Placed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='player2Placed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
