# Generated by Django 2.1.2 on 2018-11-21 17:44

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_auto_20181121_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='gameID',
        ),
        migrations.RemoveField(
            model_name='playerpieces',
            name='positions',
        ),
        migrations.AddField(
            model_name='playerpieces',
            name='iOfSquaresOfType',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerpieces',
            name='jOfSquaresOfType',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerpieces',
            name='squares',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerpieces',
            name='squaresLeft',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
            preserve_default=False,
        ),
    ]
