# Generated by Django 2.1.2 on 2018-11-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_auto_20181121_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1Forbidden',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2Forbidden',
        ),
    ]
