# Generated by Django 2.1.2 on 2018-11-22 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_auto_20181121_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpieces',
            name='whichShipsSunk',
        ),
        migrations.AlterField(
            model_name='game',
            name='player1Pieces',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player1Pieces', to='play.PlayerPieces'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2Pieces',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player2Pieces', to='play.PlayerPieces'),
        ),
    ]
