# Generated by Django 2.1.2 on 2018-11-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_auto_20181122_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1Score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='player2Score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
